"""first migration

Revision ID: 977fab88fce5
Revises: 
Create Date: 2023-05-15 14:51:02.389184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '977fab88fce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=True, nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=True, nullable=False)

    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=True, nullable=False)

    with op.batch_alter_table('data_orang_tua', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=True, nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)

    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)

    with op.batch_alter_table('data_orang_tua', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)

    # ### end Alembic commands ###