"""first migration

Revision ID: 977fab88fce5
Revises: 
Create Date: 2023-05-15 14:51:02.389184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '977fab88fce5'
down_revision = None
branch_labels = None
depends_on = None


"""def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=True, nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=True, nullable=False)

    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=True, nullable=False)

    with op.batch_alter_table('data_orang_tua', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=True, nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)

    with op.batch_alter_table('data_user', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)

    with op.batch_alter_table('data_orang_tua', schema=None) as batch_op:
        batch_op.alter_column('id', existing_type=mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)

    # ### end Alembic commands ###"""

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.alter_column('berat_lahir', existing_type=mysql.FLOAT(precision=5, scale=2), type_=mysql.FLOAT(), existing_nullable=False)

    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.alter_column('tinggi_lahir', existing_type=mysql.FLOAT(precision=5, scale=2), type_=mysql.FLOAT(), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('berat', existing_type=mysql.FLOAT(precision=5, scale=2), type_=mysql.FLOAT(), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('tinggi', existing_type=mysql.FLOAT(precision=5, scale=2), type_=mysql.FLOAT(), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('lingkar_lengan_atas', existing_type=mysql.FLOAT(precision=5, scale=2), type_=mysql.FLOAT(), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('zs_bb_umur', existing_type=mysql.FLOAT(precision=5, scale=2), type_=mysql.FLOAT(), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('zs_tb_umur', existing_type=mysql.FLOAT(precision=5, scale=2), type_=mysql.FLOAT(), existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.alter_column('berat_lahir', existing_type=mysql.FLOAT(), type_=mysql.FLOAT(precision=5, scale=2), existing_nullable=False)

    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.alter_column('tinggi_lahir', existing_type=mysql.FLOAT(), type_=mysql.FLOAT(precision=5, scale=2), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('berat', existing_type=mysql.FLOAT(), type_=mysql.FLOAT(precision=5, scale=2), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('tinggi', existing_type=mysql.FLOAT(), type_=mysql.FLOAT(precision=5, scale=2), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('lingkar_lengan_atas', existing_type=mysql.FLOAT(), type_=mysql.FLOAT(precision=5, scale=2), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('zs_bb_umur', existing_type=mysql.FLOAT(), type_=mysql.FLOAT(precision=5, scale=2), existing_nullable=False)

    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.alter_column('zs_tb_umur', existing_type=mysql.FLOAT(), type_=mysql.FLOAT(precision=5, scale=2), existing_nullable=False)

    # ### end Alembic commands ###