"""first migration

Revision ID: ef3f655a0af3
Revises: 
Create Date: 2023-05-15 11:43:54.152567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef3f655a0af3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.drop_index('id_anak')

    op.drop_table('data_gizi')
    op.drop_table('data_login')
    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.drop_index('id_orangtua')

    op.drop_table('data_anak')
    op.drop_table('data_orang_tua')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_orang_tua',
    sa.Column('id', mysql.INTEGER(display_width=255), autoincrement=False, nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('alamat', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('provinsi', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('kabupaten', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('kecamatan', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('desa', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('posyandu', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('rt', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('rw', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_anak',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nik', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('nama', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('jenis_kelamin', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('tanggal_lahir', sa.DATE(), nullable=False),
    sa.Column('berat_lahir', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('tinggi_lahir', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('id_orangtua', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_orangtua'], ['data_orang_tua.id'], name='data_anak_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('data_anak', schema=None) as batch_op:
        batch_op.create_index('id_orangtua', ['id_orangtua'], unique=False)

    op.create_table('data_login',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('data_gizi',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('id_anak', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('usia_diukur', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tanggal_pengukuran', sa.DATE(), nullable=False),
    sa.Column('berat', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('tinggi', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('lingkar_lengan_atas', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('zs_bb_umur', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('zs_bb_tb', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('bb_umur', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('bb_tb', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('naik_berat_badan', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('jumlah_vitamin_a', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_anak'], ['data_anak.id'], name='data_gizi_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('data_gizi', schema=None) as batch_op:
        batch_op.create_index('id_anak', ['id_anak'], unique=False)

    # ### end Alembic commands ###
